{% set name = "python-minifier" %}
{% set version = "2.10.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/python_minifier-{{ version }}.tar.gz
  sha256: 954cadb2489e6d1dfcc86d6cd861ede4dfbf4e9c265920671ab77b5b7f4b8617

build:
  number: 0
  noarch: python
  entry_points:
    - pyminify=python_minifier.__main__:main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.3,<=3.12
    - setuptools
  run:
    - python >=3.3,<=3.12

test:
  imports:
    - python_minifier
  commands:
    - pip check
    - pyminify --help
  requires:
    - pip

about:
  home: https://github.com/dflook/python-minifier
  summary: Transform Python source code into it's most compact representation
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
    - fritjofh
