{% set name = "python-minifier" %}
{% set version = "2.11.3" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/python_minifier-{{ version }}.tar.gz
  sha256: 489133b91212ec9658a7b64d243eb9eb67d7e53faf2ac5166a33301c61b3dcab

build:
  number: 0
  noarch: python
  entry_points:
    - pyminify=python_minifier.__main__:main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
  run:
    - python >={{ python_min }}

test:
  imports:
    - python_minifier
  commands:
    - pip check
    - pyminify --help
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/dflook/python-minifier
  summary: Transform Python source code into it's most compact representation
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
