{% set name = "python-minifier" %}
{% set version = "2.11.2" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/python_minifier-{{ version }}.tar.gz
  sha256: d933f48e3b00ab35816a7142e2c9f8130cf849500f8b968cff3f13aaaecc677b

build:
  number: 0
  noarch: python
  entry_points:
    - pyminify=python_minifier.__main__:main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.3,<3.13
    - setuptools
  run:
    - python >=3.3,<3.13

test:
  imports:
    - python_minifier
  commands:
    - pip check
    - pyminify --help
  requires:
    - pip

about:
  home: https://github.com/dflook/python-minifier
  summary: Transform Python source code into it's most compact representation
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
